const CONFIG = {
  APP_NAME: "Word Processor",
  PROJECT_VERSION: 1,
  PROJECT_EXT: ".wdoc",
  RECENT_FILES_KEY: "word-processor-recent",
  MAX_RECENT: 8,
  MAX_UNDO: 80,
  AUTOSAVE_KEY: "word-processor-autosave",
  AUTOSAVE_INTERVAL_MS: 30000,
  HISTORY_DEBOUNCE_MS: 400,
  DEFAULT_TITLE: "Untitled",
  DEFAULT_CONTENT: "<p>Start writing here…</p>",
  DEFAULT_FONT_FAMILY: "Georgia, 'Times New Roman', serif",
  DEFAULT_FONT_SIZE: 12,
  DEFAULT_LINE_HEIGHT: 1.65,
  DEFAULT_TEXT_COLOR: "#1e293b",
  DEFAULT_PAGE: {
    size: "letter",
    marginTop: 96,
    marginRight: 96,
    marginBottom: 96,
    marginLeft: 96,
  },
  PAGE_SIZES: {
    letter: { label: "US Letter", width: 816, height: 1056 },
    a4: { label: "A4", width: 794, height: 1123 },
    legal: { label: "US Legal", width: 816, height: 1344 },
  },
  FONT_FAMILIES: [
    { label: "Georgia", value: "Georgia, 'Times New Roman', serif" },
    { label: "Times New Roman", value: "'Times New Roman', Times, serif" },
    { label: "Garamond", value: "Garamond, 'Palatino Linotype', serif" },
    { label: "Segoe UI", value: "'Segoe UI', system-ui, sans-serif" },
    { label: "Arial", value: "Arial, Helvetica, sans-serif" },
    { label: "Verdana", value: "Verdana, Geneva, sans-serif" },
    { label: "Courier New", value: "'Courier New', Courier, monospace" },
  ],
  FONT_SIZES: [10, 11, 12, 14, 16, 18, 20, 24, 28, 32, 36, 48],
  HEADING_STYLES: [
    { tag: "p", label: "Normal", className: "" },
    { tag: "h1", label: "Heading 1", className: "doc-h1" },
    { tag: "h2", label: "Heading 2", className: "doc-h2" },
    { tag: "h3", label: "Heading 3", className: "doc-h3" },
  ],
  ZOOM_LEVELS: [75, 90, 100, 110, 125, 150],
  DEFAULT_ZOOM: 100,
  WORDS_PER_MINUTE: 200,
};
